PROJECT = wilma_api
DEPS = cowboy jiffy erlydtl merl
dep_cowboy = git https://github.com/ninenines/cowboy 1.0.0
dep_jiffy = git https://github.com/davisp/jiffy 0.13.2
dep_merl = git https://github.com/erlydtl/merl master
dep_erlydtl = git https://github.com/erlydtl/erlydtl 0.9.4

include erlang.mk
